name: "libxml2 vcpkg"
description: "Install libxml using vcpkg"
inputs:
  target:
    description: "Target to build for"
    required: true
    default: x64-windows

runs:
  using: "composite"
  steps:
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - name: Install libxml2 with vcpkg
      shell: pwsh
      env:
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      run: |
        vcpkg install libxml2:${{ inputs.target }}
